# Project language
language: php
php:
  - 5.6
  - 7.2

# Start mysql service
services:
  - mariadb

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  allow_failures:
    - php: 7.2

# Define an environment variable
env:
  - SYMFONY_VERSION="2.*" DB=mariadb

before_script:
  - wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
  - chmod a+x php-cs-fixer

script:
  - ./php-cs-fixer fix . —dry-run -vv —rules=@Symfony —diff

# After a build, send email notification with the build results
notifications:
  email: esgi_iw3@gmail.com
