version: '3'
services:
    mysql:
        image: 'mysql:5.7'
        ports:
            - '3306:3306'
        volumes:
            - './docker/database:/var/lib/mysql'
        environment:
            - MYSQL_DATABASE=unsecure
            - MYSQL_USER=esgi_iw3
            - MYSQL_PASSWORD=docker
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
    php:
        image: 'okty/php:7.2'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - 'PHP_EXTENSIONS=pdo_mysql,intl,opcache,apcu,xdebug'
    nginx:
        image: 'okty/nginx:1.14'
        ports:
            - '8080:80'
        volumes:
            - './:/usr/share/nginx/html'
        environment:
            - MAX_UPLOAD_SIZE=2M
            - PHP_CONTAINER_ID=php
            - INDEX_SUBFOLDER=public
